import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image, Font } from '@react-pdf/renderer';
import type { AIContextObject } from '../../lib/IntelligenceEngine';

// Optionally register a font if you have a URL, otherwise fallback to Helvetica
// Font.register({ family: 'Inter', src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.woff' });

const primaryColor = '#111827';
const accentColor = '#6366f1';
const successColor = '#10b981';
const dangerColor = '#ef4444';
const warningColor = '#f59e0b';
const textColor = '#374151';
const lightText = '#6b7280';
const borderColor = '#e5e7eb';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  coverPage: {
    padding: 40,
    fontFamily: 'Helvetica',
    backgroundColor: primaryColor,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  coverTitle: {
    fontSize: 36,
    color: '#ffffff',
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  coverSubtitle: {
    fontSize: 18,
    color: accentColor,
    marginBottom: 40,
  },
  coverDate: {
    fontSize: 14,
    color: '#9ca3af',
    marginTop: 'auto',
  },
  watermark: {
    position: 'absolute',
    bottom: 40,
    right: 40,
    fontSize: 12,
    color: 'rgba(255,255,255,0.3)',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  header: {
    fontSize: 24,
    color: primaryColor,
    fontWeight: 'bold',
    marginBottom: 20,
    borderBottom: `2px solid ${accentColor}`,
    paddingBottom: 10,
  },
  subHeader: {
    fontSize: 16,
    color: primaryColor,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 10,
  },
  text: {
    fontSize: 11,
    color: textColor,
    lineHeight: 1.6,
    marginBottom: 10,
  },
  bold: {
    fontWeight: 'bold',
  },
  kpiGrid: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  kpiCard: {
    width: '30%',
    backgroundColor: '#f9fafb',
    border: `1px solid ${borderColor}`,
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
  },
  kpiLabel: {
    fontSize: 10,
    color: lightText,
    textTransform: 'uppercase',
    marginBottom: 5,
  },
  kpiValue: {
    fontSize: 18,
    color: primaryColor,
    fontWeight: 'bold',
  },
  kpiGood: { color: successColor },
  kpiBad: { color: dangerColor },
  chartContainer: {
    width: '100%',
    marginBottom: 20,
    border: `1px solid ${borderColor}`,
    borderRadius: 8,
    padding: 10,
  },
  chartImage: {
    width: '100%',
    height: 'auto',
  },
  list: {
    marginLeft: 15,
  },
  listItem: {
    fontSize: 11,
    color: textColor,
    lineHeight: 1.6,
    marginBottom: 5,
  },
  table: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    border: `1px solid ${borderColor}`,
    borderRadius: 8,
    marginTop: 10,
  },
  tableHeader: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#f9fafb',
    borderBottom: `1px solid ${borderColor}`,
    padding: 10,
  },
  tableRow: {
    display: 'flex',
    flexDirection: 'row',
    borderBottom: `1px solid ${borderColor}`,
    padding: 10,
  },
  tableCol1: { width: '20%', fontSize: 10, color: primaryColor, fontWeight: 'bold' },
  tableCol2: { width: '50%', fontSize: 10, color: textColor },
  tableCol3: { width: '30%', fontSize: 10, color: lightText },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: lightText,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTop: `1px solid ${borderColor}`,
    paddingTop: 10,
  },
  pageNumber: {
    textAlign: 'right',
  }
});

interface BusinessReportProps {
  companyName: string;
  date: string;
  aiContext: AIContextObject;
  charts: Record<string, string>;
}

export const BusinessReportDocument: React.FC<BusinessReportProps> = ({ companyName, date, aiContext, charts }) => {
  const formatCurrency = (val: number) => `INR ${val.toLocaleString()}`;

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={styles.coverPage}>
        <Text style={styles.coverTitle}>AI Business Analysis Report</Text>
        <Text style={styles.coverSubtitle}>{companyName}</Text>
        <Text style={styles.coverDate}>Generated by PulseAI • {date}</Text>
        <Text style={styles.watermark}>Confidential</Text>
      </Page>

      {/* Executive Summary & KPI Summary */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>1. Executive Summary</Text>
        <Text style={styles.text}>
          This report provides a comprehensive overview of the business performance for the selected period. 
          The overall business health score is <Text style={styles.bold}>{aiContext.healthScore}/100</Text>, 
          classifying the business as <Text style={styles.bold}>{aiContext.grade}</Text>.
        </Text>
        
        <Text style={styles.subHeader}>Key Performance Indicators</Text>
        <View style={styles.kpiGrid}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Revenue</Text>
            <Text style={styles.kpiValue}>{formatCurrency(aiContext.revenue)}</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Expenses</Text>
            <Text style={styles.kpiValue}>{formatCurrency(aiContext.expenses)}</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Profit Margin</Text>
            <Text style={[styles.kpiValue, aiContext.profitMargin > 15 ? styles.kpiGood : styles.kpiBad]}>
              {aiContext.profitMargin}%
            </Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Cash Flow</Text>
            <Text style={[styles.kpiValue, aiContext.cashFlow > 0 ? styles.kpiGood : styles.kpiBad]}>
              {formatCurrency(aiContext.cashFlow)}
            </Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Revenue Growth</Text>
            <Text style={[styles.kpiValue, aiContext.revenueGrowth > 0 ? styles.kpiGood : styles.kpiBad]}>
              {aiContext.revenueGrowth}%
            </Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Customer Retention</Text>
            <Text style={styles.kpiValue}>{aiContext.customerRetention}</Text>
          </View>
        </View>

        <Text style={styles.subHeader}>Performance Assessment</Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Financial Score: {aiContext.financialScore}/100 - {aiContext.explanations.financial}</Text>
          <Text style={styles.listItem}>• Inventory Score: {aiContext.inventoryScore}/100 - {aiContext.explanations.inventory}</Text>
          <Text style={styles.listItem}>• Customer Score: {aiContext.customerScore}/100 - {aiContext.explanations.customer}</Text>
          <Text style={styles.listItem}>• Growth Score: {aiContext.growthScore}/100 - {aiContext.explanations.growth}</Text>
          <Text style={styles.listItem}>• Operations Score: {aiContext.operationsScore}/100 - {aiContext.explanations.operations}</Text>
        </View>

        <View style={styles.footer} fixed>
          <Text>{companyName} - AI Business Report</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>

      {/* Charts Section */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>2. Financial & Growth Charts</Text>
        {charts.revenueTrend && (
          <View style={styles.chartContainer} wrap={false}>
            <Text style={styles.subHeader}>Revenue Trend</Text>
            <Image src={charts.revenueTrend} style={styles.chartImage} />
          </View>
        )}
        {charts.profitExpense && (
          <View style={styles.chartContainer} wrap={false}>
            <Text style={styles.subHeader}>Profit vs Expenses</Text>
            <Image src={charts.profitExpense} style={styles.chartImage} />
          </View>
        )}
        {charts.salesGrowth && (
          <View style={styles.chartContainer} wrap={false}>
            <Text style={styles.subHeader}>Sales Growth</Text>
            <Image src={charts.salesGrowth} style={styles.chartImage} />
          </View>
        )}
        <View style={styles.footer} fixed>
          <Text>{companyName} - AI Business Report</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>

      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>3. Operations & Customer Charts</Text>
        {charts.inventory && (
          <View style={styles.chartContainer} wrap={false}>
            <Text style={styles.subHeader}>Inventory Distribution</Text>
            <Image src={charts.inventory} style={styles.chartImage} />
          </View>
        )}
        {charts.revenueSources && (
          <View style={styles.chartContainer} wrap={false}>
            <Text style={styles.subHeader}>Revenue Sources</Text>
            <Image src={charts.revenueSources} style={styles.chartImage} />
          </View>
        )}
        {charts.cashFlow && (
          <View style={styles.chartContainer} wrap={false}>
            <Text style={styles.subHeader}>Cash Flow Analysis</Text>
            <Image src={charts.cashFlow} style={styles.chartImage} />
          </View>
        )}
        <View style={styles.footer} fixed>
          <Text>{companyName} - AI Business Report</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>

      {/* AI Insights & Recommendations */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>4. AI Insights & Strategy</Text>
        
        <Text style={styles.subHeader}>Key Business Strengths</Text>
        <View style={styles.list}>
          {aiContext.topStrengths.map((str, i) => (
            <Text key={i} style={styles.listItem}>• {str}</Text>
          ))}
        </View>

        <Text style={styles.subHeader}>Primary Business Risks</Text>
        <View style={styles.list}>
          {aiContext.topRisks.map((risk, i) => (
            <Text key={i} style={styles.listItem}>• {risk}</Text>
          ))}
        </View>

        <Text style={styles.header} break>5. Action Plan & Recommendations</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.tableCol1}>Priority</Text>
            <Text style={styles.tableCol2}>Recommendation</Text>
            <Text style={styles.tableCol3}>Expected Impact</Text>
          </View>
          {aiContext.recommendations.map((rec, i) => {
            const priority = i === 0 ? 'High' : i === 1 ? 'Medium' : 'Standard';
            return (
              <View style={styles.tableRow} key={i}>
                <Text style={styles.tableCol1}>{priority}</Text>
                <Text style={styles.tableCol2}>{rec}</Text>
                <Text style={styles.tableCol3}>Improves {aiContext.grade === 'Critical' ? 'Survival' : 'Growth'}</Text>
              </View>
            );
          })}
        </View>

        <Text style={styles.header} break>6. PulseAI Conclusion</Text>
        <Text style={styles.text}>
          Based on the analyzed data, the business exhibits a {aiContext.healthScore}/100 health index. 
          The structural fundamentals are {aiContext.healthScore > 70 ? 'strong' : 'under pressure'}, driven heavily by 
          the profit margin of {aiContext.profitMargin}% and revenue growth of {aiContext.revenueGrowth}%. 
          Moving forward, it is critical to address the outlined risks, primarily focusing on 
          {aiContext.topRisks.length > 0 ? aiContext.topRisks[0].toLowerCase() : 'operational inefficiencies'}. 
          If the provided action plan is implemented, we project a positive trend trajectory in the subsequent periods.
        </Text>

        <View style={styles.footer} fixed>
          <Text>{companyName} - AI Business Report</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
};
